# 基金列表配置文件
# 支持两种配置方式：持有基金和关注基金

# 持有基金 - 重点监控
owned_funds:
  - code: "000001"
    name: "华夏成长混合"
    purchase_price: 2.8000
    purchase_date: "2024-02-20"
  
  - code: "110022"
    name: "易方达消费行业"
    purchase_price: 3.1500
    purchase_date: "2024-01-15"
  
  - code: "519066"
    name: "汇添富蓝筹稳健"
    purchase_price: 3.2000
    purchase_date: "2024-03-10"

# 关注基金 - 潜在投资目标
watchlist_funds:
  - code: "001717"
    name: "工银前沿医疗股票"
    reason: "医疗健康主题，长期看好"
  
  - code: "005827"
    name: "易方达蓝筹精选混合"
    reason: "蓝筹股投资，稳健增长"
  
  - code: "001156"
    name: "申万菱信新能源汽车"
    reason: "新能源汽车主题，未来趋势"
  
  - code: "161725"
    name: "招商中证白酒指数"
    reason: "白酒行业指数，消费升级"

# 基金分组配置
groups:
  equity:  # 股票型基金
    - "110022"
    - "001717"
    - "001156"
  
  mixed:  # 混合型基金
    - "000001"
    - "519066"
    - "005827"
  
  index:  # 指数型基金
    - "161725"
